### PR TITLE
CI: iterate with circleci until it works

### LINKED ISSUE #46: CI: Upload html build artifacts for inspection of website based on PR build
The only CI check we currently have (recently migrated from Travis to GH actions) is a quick "build test": https://github.com/BIDS-Apps/bids-apps.github.io/blob/c881455dec3cfa966e70b64b8bb8b595d93ca52d/.github/workflows/ruby_tests.yml#L1

I think it'd be cool to extend this by uploading the html artifacts for inspection. Doing this on GH Actions is slightly inconvenient, because one always has to download a zip file and then look at it.

With circleci and https://github.com/larsoner/circleci-artifacts-redirector, this can be made much more convenient (just click on the check, and view artifacts in the browser)

### PR DESCRIPTION
**Pull request by sappelhoff**
closes #46 

preferably fixed and merged before #54 so that we can better judge the impact of changes

the CI works, but the website is slightly weird:

1. there is no "landing page" I could point to
2. when building locally, and when looking at the CI output, it seems like CSS is missing ... but in the GH pages output, this is fine. -- probably something is wrong with the paths.

### CODE REVIEW

**Review by sappelhoff — COMMENTED** [review]
It would probably help to know which "template" the website is based on (if any), or if it was written just for this.

I wouldn't be opposed to changing the entire website to a very straight forward template that contains a good documentation. We have minimal needs and I feel like the current structure is overly complicated and contains lots of [cruft](https://en.wikipedia.org/wiki/Cruft)

PS: This is not to step on anyone's toes ... it's just hard to make it work with the minimal knowledge I have and without documentation :-)

**Comment by Remi-Gau** [comment]
>     1. there is no "landing page" I could point to

That is fixable

>     2. when building locally, and when looking at the CI output, it seems like CSS is missing ... but in the GH pages output, this is fine. -- probably something is wrong with the path

Not sure if this is doable with jekyll (that github pages uses in the background).

I think that `jekyll serve` takes care of linking the html and the css.

**Comment by Remi-Gau** [comment]
> I wouldn't be opposed to changing the entire website to a very straight forward template that contains a good documentation. We have minimal needs and I feel like the current structure is overly complicated

I actually think that most templates will bring even more stuff to be honest.

**Comment by sappelhoff** [comment]
> I think that jekyll serve takes care of linking the html and the css.

true ... when running `bundle exec jekyll serve` it works as expected. Whereas opening the html files in a browser after `bundle exec jekyll build` does **not** work :thinking: 

> Not sure if this is doable with jekyll (that github pages uses in the background).

it works on https://github.com/bids-standard/bids-website/ -- so I think we are just missing something here.

> I actually think that most templates will bring even more stuff to be honest.

okay, maybe I should just dig a little deeper into general jekyll docs then.

**Comment by Remi-Gau** [comment]
> Perhaps I should try out netlify? Any experience with that @Remi-Gau?
> 
> https://docs.netlify.com/site-deploys/deploy-previews/

That's what the OHBM OSSIG website used but I feel that maybe then swtiching to another template that will render things properly could be an option.

All in all I don't think this is super urgent in any case because it is not like this website gets updated daily.

So I am also fine leaving this one open until we have the patience to get back to it.

**Comment by sappelhoff** [comment]
> but I feel that maybe then swtiching to another template that will render things properly could be an option.

I also think so

> All in all I don't think this is super urgent in any case because it is not like this website gets updated daily.

agreed

> So I am also fine leaving this one open until we have the patience to get back to it.

I think I'll revert the non-functional circleci stuff and close this then :-) it was worth a try

**Pull request merged**
