### PR TITLE
Add pennlinc/toy_bids_app app

### PR DESCRIPTION
**Pull request by yarikoptic**
attn @zhao-cy  and @asmacdo please take over if there is more todo

### CODE REVIEW

**Comment by yarikoptic** [comment]
> Hi Yarik! Thank you so much for adding the toy BIDS App here! I made some modifications in the `_config.yml`, as toy BIDS App can also work on derivatives data + other imaging data types.

awesome, thank you, committed!

**Comment by yarikoptic** [comment]
I might be committing the crime, but I promise to fix it if universe get broken -- let's merge and see where we end up

**Comment by Remi-Gau** [comment]
https://www.hasthelargehadroncolliderdestroyedtheworldyet.com/

**Comment by yarikoptic** [comment]
http://www.oneukrainian.com/likesfrenchhumor/

**Comment by Remi-Gau** [comment]
http://are-you-shitting-me.urbanup.com/1718513

**Pull request merged**
