### PR TITLE
[ENH] update app badges

### LINKED ISSUE #88: add a badge with docker image size
### Your idea

Docker Image Size (latest by date)

Docker Image Size (latest by date)

### PR DESCRIPTION
**Pull request by Remi-Gau**
closes #88 

- also refactor table code
- simplify app name displayed in table
- add a badge for docker image size
- rm badge for PR

### CODE REVIEW

**Review by sappelhoff — COMMENTED** [review]
nice, thank you Remi -- I think this is useful information. 

Do you agree that we should get rid of the "open bug pull requests" badge?

I feel like this information is highly redundant with the "last commit" and "open issues" information

**Comment by Remi-Gau** [comment]
> nice, thank you Remi -- I think this is useful information.
> 
> Do you agree that we should get rid of the "open bug pull requests" badge?
> 
> I feel like this information is highly redundant with the "last commit" and "open issues" information

agreed

should I do this in this PR?

**Comment by sappelhoff** [comment]
> should I do this in this PR?

Yes please, if it's not too much effort. And then we can adjust the PR title and it'll still be fine :)

**Comment by Remi-Gau** [comment]
done

**Review by sappelhoff — APPROVED** [review]

**Comment by sappelhoff** [comment]
thanks! :tada:

**Pull request merged**
