### PR TITLE
[ENH] update logo and favicon

### LINKED ISSUE #52: Where does the logo come from? -- and: revamping of background image + logo?
There is currently this logo for the BIDS-Apps organization:

image

- https://github.com/BIDS-Apps/bids-apps.github.io/blob/master/images/gear.jpg

I wonder where it comes from, how it is licensed, and whether we should change it to just the BIDS logo.

---

Furthermore, there is currently this background image on the website:

image

- https://github.com/BIDS-Apps/bids-apps.github.io/blob/master/images/cover.jpg

I think we can probably do without it -- it's okay to have it, but it's not really related to "anything BIDS-Apps".

### PR DESCRIPTION
**Pull request by Remi-Gau**
closes #52 

Made this new logo. WDYT?

BIDS_apps_logo_black

### CODE REVIEW

**Comment by sappelhoff** [comment]
I like it. I have thought about placing the gear next to the BIDS logo instead, but that'd probably be a bit too wide ... and maybe also seem like two logos next to each other. I think what you propose here is nice.

Is the license for the "gear" public domain? I wouldn't want to get caught up with always having to cite some other icon/logo when we show our logo.

**Comment by Remi-Gau** [comment]
> Is the license for the "gear" public domain?

oops.

forgot to check.

probably better to try to use an icon from one of the many public libraries of icon.

also just realized the gear is not the same black as the BIDS logo...

**Comment by ericearl** [comment]
@Remi-Gau I think it's fun!  I'm not sure it's necessary though...

Alternative suggestion: If we have access to the same font that is used in **BIDS** in the normal logo we could place the word **APP** or **APPS** immediately below the brain and folders logo.  Then our sweet "old" logo is still intact and not obscured.

@bendhouseart: I forget, didn't you say you had some graphic design know-how?

**Comment by ericearl** [comment]
@Remi-Gau Even just a close **BOLD AND CAPITAL FONT** would probably do the trick.

**Comment by sappelhoff** [comment]
> Alternative suggestion: If we have access to the same font that is used in BIDS in the normal logo we could place the word APP or APPS immediately below the brain and folders logo. Then our sweet "old" logo is still intact and not obscured.

looking back at this a couple of days later, I think I agree --> this might be the easiest way forward

> Yeah thought of using the same font but I am not sure it even exists as a font per se...

the "BIDS" was probably hand drawn (I could imagine) -- but the "brain imaging data structure" probably wasn't, and we could use that font (or one that looks indistinguishably similar)

image

I tried my luck with https://www.myfonts.com/WhatTheFont/ and it suggested "stem regular", which unfortunately seems proprietary: https://www.myfonts.com/fonts/paratype/stem/regular/

But I think in general this would be a nice way to go

**Comment by Remi-Gau** [comment]
Quick question: do we want the bids apps favicon (or the one used as profile picture) to be the same as for BIDS without the gear?
Was just thinking that it may help distinguish them.

**Comment by sappelhoff** [comment]
I would have thought the favicon and logo (e.g., for the GH org) could indeed be just the brain+filetree thing with "APPs" written right below, as suggested by Eric.

But I also won't oppose the original "gear on top of brain+filetree" idea -- given that we use a "gear" icon that is in the public domain.

**Comment by Remi-Gau** [comment]
Very unlikely the "apps" will be legible in the favicon of a browser. :-p

**Comment by Remi-Gau** [comment]
Used this gear icon which is public domain.

https://commons.wikimedia.org/wiki/Category:SVG_gear_icons#/media/File:Font_Awesome_5_solid_cog.svg

And updated the color.

Final look is this.


android-chrome-192x192

I would say we merge and add text below later if we feel like it.

**Review by sappelhoff — APPROVED** [review]

**Pull request merged**
